//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public int userInfoId { get; set; }
        public string userInfoLastName { get; set; }
        public string userInfoFirstName { get; set; }
        public string userInfoAddress { get; set; }
        public string userInfoEmailAddress { get; set; }
        public Nullable<int> userId { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
